version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: frontend-container
    ports:
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_ENABLE_CORS_DEBUG=true
      - DOCKER_ENV=true
    restart: unless-stopped
    # Для всех платформ: добавляем хост-машину в extra_hosts
    extra_hosts:
      - "host.docker.internal:host-gateway" 