apiVersion: v1
kind: Secret
metadata:
  name: go-init-secrets
type: Opaque
stringData:
  POSTGRES_USER: go_init_usr
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: go_init_manager_db
  MINIO_ROOT_USER: B6NZaLCC7AmyqSkdB2Rr
  MINIO_ROOT_PASSWORD: C8gZg0GSg31mEUs3BRVj7Dh5nIZ4HCvMPEHEamYq
