services:
  # ---------- METRICS STACK ----------
  prometheus:
    image: prom/prometheus:v3.10.0
    container_name: go_init_prometheus
    profiles: ["observe"]
    ports: ["9090:9090"]
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: ["go-init-networks"]

  grafana:
    image: grafana/grafana:12.4.0
    container_name: go_init_grafana
    profiles: ["observe"]
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - go_init_grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    networks: ["go-init-networks"]

  nodeexporter:
    image: prom/node-exporter:v1.10.2
    container_name: go_init_nodeexporter
    profiles: ["observe"]
    ports: ["9100:9100"]
    networks: ["go-init-networks"]

  # ---------- LOGS STACK ----------
  loki:
    image: grafana/loki:3.4.2
    container_name: go_init_loki
    profiles: ["observe"]
    ports: ["3100:3100"]
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - go_init_loki_data:/loki
    networks: ["go-init-networks"]

  promtail:
    image: grafana/promtail:3.4.2
    container_name: go_init_promtail
    profiles: ["observe"]
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./observability/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks: ["go-init-networks"]

  # ---------- LOAD GENERATOR ----------
# ───────── LOAD-GENERATOR ──────────────────────────────────────────────
  k6:
    profiles: ["load"]
    image: grafana/k6:1.6.1
    volumes:
      - ./k6:/scripts               # там лежит full_flow.js
    environment:
      - API_URL=http://go_init_manager:60013/graphql
    command: >
        run /scripts/full_flow.js
        --out json=/scripts/metrics.json
        --summary-export=/scripts/summary.json
    depends_on:
      - go_init_manager
    networks: ["go-init-networks"]

volumes:
  go_init_grafana_data:
  go_init_loki_data:
