apiVersion: v1
kind: ConfigMap
metadata:
  name: generator-config
data:
  config.yml: |
    grpc_client:
      service_id: "go-init-publisher"
      address: "go-init-publisher:60024"
      use_tls: false

    logger:
      level: DEBUG
      format: json

    postgres_db:
      host: postgres
      port: 5432
      database_name: go_init_generator_db
      user: go_init_usr
      password: 1234
      ssl: disable
      schema: go_init
      timezone: "Europe/Moscow"
      auto_migrate: true

    kafka:
      enabled: true
      addresses:
        - "go-init-kafka:29092"
      producer_config:
        enabled: false
        topics:
          - id: go-init-processing
            name: go-init-processing
            is_enabled: false
      consumer_config:
        enabled: true
        topics:
          - id: go-init-processing
            name: go-init-processing
            is_enabled: true
        group_id: go-init-generator-group
        auto_commit: false
