// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: go-init-manager.proto

// Имя протокольного пакета (то, что после `package`) может быть любым,
// это не обязательно совпадает с go_package:

package go_init_generate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateGenerationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Уникальный идентификатор запроса
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // Новый статус ("completed", "failed" и т.д.)
	ZipUrl    string `protobuf:"bytes,3,opt,name=zip_url,json=zipUrl,proto3" json:"zip_url,omitempty"`          // URL архива в хранилище (если генерация завершена)
}

func (x *UpdateGenerationStatusRequest) Reset() {
	*x = UpdateGenerationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_init_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGenerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenerationStatusRequest) ProtoMessage() {}

func (x *UpdateGenerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_init_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenerationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateGenerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_go_init_manager_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateGenerationStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateGenerationStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateGenerationStatusRequest) GetZipUrl() string {
	if x != nil {
		return x.ZipUrl
	}
	return ""
}

type UpdateGenerationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешно ли обновление
}

func (x *UpdateGenerationStatusResponse) Reset() {
	*x = UpdateGenerationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_init_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGenerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenerationStatusResponse) ProtoMessage() {}

func (x *UpdateGenerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_init_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenerationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateGenerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_go_init_manager_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateGenerationStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_go_init_manager_proto protoreflect.FileDescriptor

var file_go_init_manager_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x6f, 0x2d, 0x69, 0x6e, 0x69, 0x74, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6f, 0x0a, 0x1d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x7a, 0x69, 0x70, 0x55, 0x72, 0x6c, 0x22, 0x3a, 0x0a, 0x1e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x71, 0x0a, 0x0e, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x16, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67,
	0x6f, 0x2d, 0x69, 0x6e, 0x69, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f, 0x2d, 0x69, 0x6e, 0x69, 0x74, 0x2d, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x3b, 0x67, 0x6f, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_init_manager_proto_rawDescOnce sync.Once
	file_go_init_manager_proto_rawDescData = file_go_init_manager_proto_rawDesc
)

func file_go_init_manager_proto_rawDescGZIP() []byte {
	file_go_init_manager_proto_rawDescOnce.Do(func() {
		file_go_init_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_init_manager_proto_rawDescData)
	})
	return file_go_init_manager_proto_rawDescData
}

var file_go_init_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_init_manager_proto_goTypes = []interface{}{
	(*UpdateGenerationStatusRequest)(nil),  // 0: pb.UpdateGenerationStatusRequest
	(*UpdateGenerationStatusResponse)(nil), // 1: pb.UpdateGenerationStatusResponse
}
var file_go_init_manager_proto_depIdxs = []int32{
	0, // 0: pb.ManagerService.UpdateGenerationStatus:input_type -> pb.UpdateGenerationStatusRequest
	1, // 1: pb.ManagerService.UpdateGenerationStatus:output_type -> pb.UpdateGenerationStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_init_manager_proto_init() }
func file_go_init_manager_proto_init() {
	if File_go_init_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_init_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGenerationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_init_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGenerationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_init_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_init_manager_proto_goTypes,
		DependencyIndexes: file_go_init_manager_proto_depIdxs,
		MessageInfos:      file_go_init_manager_proto_msgTypes,
	}.Build()
	File_go_init_manager_proto = out.File
	file_go_init_manager_proto_rawDesc = nil
	file_go_init_manager_proto_goTypes = nil
	file_go_init_manager_proto_depIdxs = nil
}
